---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-runner-additions
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'  
- apiGroups:
  - "eventing.knative.dev"
  resources:
  - triggers
  verbs:
  - '*'  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-runner-additions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-runner-additions
subjects:
- kind: ServiceAccount
  name: pipeline-runner
  namespace: kubeflow

